[package]
name = "macro3_client"
version = "0.1.0"
authors = ["Katacoda Scenario <scenario@katacoda.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro3_derive = { path = "../macro3" }